// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VistaAzul.Modelos;

#nullable disable

namespace VistaAzul.Migrations
{
    [DbContext(typeof(VistaAzulDbContext))]
    partial class VistaAzulDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmaDeLlavesHabitacion", b =>
                {
                    b.Property<int>("AmasDeLlavesId")
                        .HasColumnType("int");

                    b.Property<int>("HabitacionesNumero")
                        .HasColumnType("int");

                    b.HasKey("AmasDeLlavesId", "HabitacionesNumero");

                    b.HasIndex("HabitacionesNumero");

                    b.ToTable("HabitacionAmaDeLlaves", (string)null);
                });

            modelBuilder.Entity("VistaAzul.Modelos.AmaDeLlaves", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreApellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CI")
                        .IsUnique();

                    b.ToTable("AmasDeLlaves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CI = "85031445678",
                            NombreApellidos = "Elena Garcia Fernandez",
                            NumeroTelefono = "+5353334445"
                        },
                        new
                        {
                            Id = 2,
                            CI = "89110298765",
                            NombreApellidos = "Rosa Martinez Perez",
                            NumeroTelefono = "+5355556667"
                        });
                });

            modelBuilder.Entity("VistaAzul.Modelos.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("EsVIP")
                        .HasColumnType("bit");

                    b.Property<string>("NombreApellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CI")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CI = "99010212345",
                            EsVIP = false,
                            NombreApellidos = "Juan Perez Gomez",
                            NumeroTelefono = "+5352345678"
                        },
                        new
                        {
                            Id = 2,
                            CI = "95051254321",
                            EsVIP = true,
                            NombreApellidos = "Maria Carmen Rodriguez",
                            NumeroTelefono = "+5358765432"
                        },
                        new
                        {
                            Id = 3,
                            CI = "98122598765",
                            EsVIP = false,
                            NombreApellidos = "Carlos Diaz Gutierrez",
                            NumeroTelefono = "+5351112223"
                        });
                });

            modelBuilder.Entity("VistaAzul.Modelos.Habitacion", b =>
                {
                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("EstaFueraDeServicio")
                        .HasColumnType("bit");

                    b.HasKey("Numero");

                    b.ToTable("Habitaciones");

                    b.HasData(
                        new
                        {
                            Numero = 11,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 12,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 13,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 14,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 15,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 21,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 22,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 23,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 24,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 25,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 31,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 32,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 33,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 34,
                            EstaFueraDeServicio = false
                        },
                        new
                        {
                            Numero = 35,
                            EstaFueraDeServicio = false
                        });
                });

            modelBuilder.Entity("VistaAzul.Modelos.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaCancelada")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaElClienteEnHostal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReservacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitacionNumero")
                        .HasColumnType("int");

                    b.Property<double>("Importe")
                        .HasColumnType("float");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("HabitacionNumero");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("VistaAzul.Modelos.Traza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Trazas");
                });

            modelBuilder.Entity("AmaDeLlavesHabitacion", b =>
                {
                    b.HasOne("VistaAzul.Modelos.AmaDeLlaves", null)
                        .WithMany()
                        .HasForeignKey("AmasDeLlavesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VistaAzul.Modelos.Habitacion", null)
                        .WithMany()
                        .HasForeignKey("HabitacionesNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VistaAzul.Modelos.Reserva", b =>
                {
                    b.HasOne("VistaAzul.Modelos.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VistaAzul.Modelos.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("VistaAzul.Modelos.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("VistaAzul.Modelos.Habitacion", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
